version: "3.5"
services:
    fuseki:
        image: stain/jena-fuseki-ps
        container_name: example_fuseki
        restart: always
        ports:
            - "32769:3030"
        volumes:
            - "./volumes/fuseki_data:/fuseki"
        environment:
            ADMIN_PASSWORD: st_FuSeKi!